import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import NavigationBar from "./components/NavigationBar";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-background dark:bg-dark-background duration-150 min-h-screen ${inter.className}`}
      >
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
